# config/packages/security.yaml

security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~ 
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            user_checker: App\Security\UserChecker

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # possible values: 'strict', 'lax' and null
                samesite: 'strict'
                # https://symfony.com/doc/current/security/remember_me.html

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html
            logout:
                path: security_logout
                target: /
                handlers: [app.logout.listener]

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # require ROLE_ADMIN for /admin*
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/wachtwoord-vergeten, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/beheer, roles: ROLE_SUPERADMIN }
         - { path: ^/profiel, roles: ROLE_USER }

    role_hierarchy:
      ROLE_ADMIN:        ROLE_USER 
      ROLE_SUPERADMIN:   [ROLE_ADMIN]
