twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locale: '%locale%'
        timezone: '%timezone%'
        webmaster: '%app.mailer.from%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
