# This file sets the configuration of the 'Category' entity.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        BlogPost:
            class: App\Entity\BlogPost
            label: 'Blog :: post'
            list:
                fields:
                    - { property: 'id', label: 'Id' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'image', type: 'image', label: 'Afbeelding', base_path: '%app.path.img.blogPost%' }
                    - { property: 'category', label: 'Categorie' }
                    - { property: 'special', label: 'Voorpagina' }
                    - { property: 'pinned', label: 'Pin', type: 'boolean' }
                    - { property: 'publishAt', label: 'Gepubliceerd op' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['publishAt', 'DESC']
            form:
                fields:
                    - { type: 'group', label: 'Basisgegevens', icon: 'pencil', css_class: "col-xs-12 col-md-9" }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'titleShort', label: 'Verkorte titel' }
                    - { property: 'body', label: 'Tekst', type: 'fos_ckeditor', css_class: 'w-100', type_options: { config_name: 'standard' } } 
                    - { type: 'group', label: 'Opties', icon: 'cog', css_class: "col-xs-12 col-md-3"  }
                    - { property: 'enabled', label: 'Actief' }
                    - { property: 'special', label: 'Voorpagina' }
                    - { property: 'pinned', label: 'Vastgepind' }
                    - { property: 'archived', label: 'Gearchiveerd' }
                    - { property: 'category', label: 'Categorie', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] } }
                    - { property: 'author', label: 'Auteur', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] } }
                    - { property: 'publishAt', label: 'Publiceer vanaf' }
                    - { property: 'description', label: 'Korte omschrijving', type: 'textarea' }
                    - { property: 'event', label: 'Kalender event', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getFilteredCalendarEvents'] } }
                    - { property: 'imageFile', type: 'vich_image', label: 'Afbeelding', base_path: '%app.path.img.blogPost%' }
                    - { property: 'documentFile', type: 'vich_file', label: 'Bijlage', base_path: '%app.path.doc.blogPost%' }
                    - { property: 'keywords', label: 'Keywords' }
            edit:
                actions: ['delete']

        BlogCategory:
            class: App\Entity\BlogCategory
            label: 'Blog :: categorie'
            list:
                fields:
                    - { property: 'id', label: 'Id' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'description', label: 'Korte omschrijving' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['id', 'ASC']
            form:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'description', label: 'Korte omschrijving', type: 'textarea' }
                    - { property: 'enabled', label: 'Actief' }
            edit:
                fields:
                    - { property: 'slug', label: 'Slug' }
