# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        CarouselSlide:
            class: App\Entity\CarouselSlide
            label: 'Carousel'
            list:
                fields:
                    - { property: 'enabled', label: 'Actief' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'showTitle', label: 'Toon titel' }
                    - { property: 'image', type: 'image', label: 'Afbeelding', base_path: '%app.path.img.carousel%' }
                    - { property: 'publishAt', label: 'Publiceer vanaf' }
                    - { property: 'publishUntil', label: 'Publiceer tot' }
                sort: ['id', 'ASC']
            form:
                fields:
                    - { type: 'group', label: 'Basisgegevens', icon: 'pencil', css_class: "col-xs-12 col-md-9" }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'body', label: 'Tekst', type: 'fos_ckeditor', css_class: 'w-100', type_options: { config_name: 'minimal' } } 
                    - { type: 'group', label: 'Opties', icon: 'cog', css_class: "col-xs-12 col-md-3" }
                    - { property: 'enabled', label: 'Actief' }
                    - { property: 'showTitle', label: 'Toon titel' }
                    - { property: 'overlay', label: 'Achtergrond donkerder maken' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Afbeelding', base_path: '%app.path.img.carousel%' }
                    - { property: 'publishAt', label: 'Publiceer vanaf' }
                    - { property: 'publishUntil', label: 'Publiceer tot' }
                    - { property: 'event', label: 'Kalender event', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getFilteredCalendarEvents'] } }
                    - { property: 'url', label: 'Externe url' }
                    - { property: 'urlButton', label: 'Naam externe url', type_options: { attr: { maxlength: 20 } } }
            edit:
                actions: ['delete']
