# config/routes.yaml

#security
security_logout:
    path: /loguit
    methods: GET

# calendar
calendar:
    path: /kalender
    controller: App\Controller\PageController::calendar

calendar_list:
    path: /kalender/{year<\d+>}
    controller: App\Controller\PageController::calendar_list

calendar_event:
    path: /kalender/{uuid<^[a-zA-Z0-9]{16}$>}
    controller: App\Controller\PageController::calendar_event

# contact
contact_form:
    path: /contact
    controller: App\Controller\PageController::contact_form

contact_faq:
    path: /faq
    controller: App\Controller\PageController::contact_faq

# general content
blog:
    path: /blog
    controller: App\Controller\PageController::blog_category

blog_post:
    path: /blog/{id<\d+>?1}/{slug?}
    controller: App\Controller\PageController::blog_post

blog_category:
    path: /blog/{slug}
    controller: App\Controller\PageController::blog_category

static_page:
    path: /{slug}
    controller: App\Controller\PageController::static_page
